name: Maintain Branches

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale branches
        uses: LucasAzevedo23/maintain-remove-stale-branches@0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          days_to_stale: 15
      - name: Delete marked branches
        uses: noh4nsen/delete-stale-branches@0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
